### ISSUE TITLE
Zend_Config_Yaml broken

### ISSUE THREAD

**Issue by blinktag** [Shardj/zf1-future#20]
https://github.com/Shardj/zf1-future/commit/3e9b26c748282204a3d5193aac5c948cac40c1da#diff-9235a8f0d83484e2adcf78f7ebffe2caL292

This change broke `Zend_Config_Yaml` because the class was using the internal array pointer to handle the loop's search space with `each()` and `prev()`. Since PHP7 `foreach` no longer respects the internal array pointer, so adding `next()` in the loop wouldn't help either 

I have attempted my best at solving this issue by using `array_slice()` to handle the loop's search space in https://gist.github.com/blinktag/b2757d9f20177237b21b0270436b6009

It now correctly handles the following yaml:

```yaml
development:
  maindb:
    default:  true
    host:     data.server.com.local
    username: db_user
    password: -
    dbname:   db_development
    adapter:  pdo_mysql
    profiler:
      enabled: true
      class: Zend_Db_Profiler
```

However it duplicates maindb's sub-values in the root of the config object, and I haven't been able to figure this part out:

```php
$database_config = new Zend_Config_Yaml('database.yml', APPLICATION_ENV);
dump($database_config);

Zend_Config_Yaml {#17 ▼
  #_skipExtends: false
  #_yamlDecoder: array:2 [▶]
  #_allowModifications: false
  #_index: 0
  #_count: 10
  #_data: array:10 [▼
    "maindb" => Zend_Config {#18 ▼
      #_allowModifications: false
      #_index: 0
      #_count: 9
      #_data: array:9 [▼
        "default" => true
        "host" => "data.server.com.local"
        "username" => "db_user"
        "password" => "-"
        "dbname" => "db_development"
        "adapter" => "pdo_mysql"
        "profiler" => Zend_Config {#20 ▶}
        "enabled" => true
        "class" => "Zend_Db_Profiler"
      ]
      #_skipNextIteration: null
      #_loadedSection: null
      #_extends: []
      #_loadFileErrorStr: null
    }
    "default" => true
    "host" => "data.server.com.local"
    "username" => "db_user"
    "password" => "-"
    "dbname" => "db_development"
    "adapter" => "pdo_mysql"
    "profiler" => Zend_Config {#21 ▶}
    "enabled" => true
    "class" => "Zend_Db_Profiler"
  ]
  #_skipNextIteration: null
  #_loadedSection: "development"
  #_extends: []
  #_loadFileErrorStr: null
}
```

Perhaps someone with better recursion skills can take a look at this

**Comment by Shardj** [comment]
Thanks I'll take a look

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/commit/b74c432fbbddfbf61bb6f84b49840126180be0df

Should be fixed

**Comment by blinktag** [comment]
Thanks for the quick turnaround! Seems to still be borked when dealing with multiple subkeys.

Example:

```yaml
development:
  maindb:
    default:  true
    host:     data.server.com.local
    username: db_user
    password: -
    dbname:   db_development
    adapter:  pdo_mysql
    profiler:
      enabled: true
      class: Zend_Db_Profiler
  otherdb:
    default:  true
    host:     data.server.com.local
    username: db_user
    password: -
    dbname:   other_development
    adapter:  pdo_mysql
```

Will return only

```php
Zend_Config_Yaml {#21 ▼
  #_skipExtends: false
  #_yamlDecoder: array:2 [▶]
  #_allowModifications: false
  #_index: 0
  #_count: 1
  #_data: array:1 [▼
    "maindb" => Zend_Config {#26 ▼
      #_allowModifications: false
      #_index: 0
      #_count: 7
      #_data: array:7 [▼
        "default" => true
        "host" => "data.server.com.local"
        "username" => "db_user"
        "password" => "-"
        "dbname" => "db_development"
        "adapter" => "pdo_mysql"
        "profiler" => Zend_Config {#25 ▶}
      ]
      #_skipNextIteration: null
      #_loadedSection: null
      #_extends: []
      #_loadFileErrorStr: null
    }
  ]
  #_skipNextIteration: null
  #_loadedSection: "development"
  #_extends: []
  #_loadFileErrorStr: null
}
```

It ignores `otherdb` and any other subkeys after the first subkey for some reason
